services:
  node1-clef:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node1-volume
        target: /root/.ethereum
        read_only: true
      - type: volume
        source: clef-node1-volume
        target: /root/.clef
      - type: bind
        source: clef-node1/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: clef-node/rules.js
        target: /root/rules.js
        read_only: true
      - type: bind
        source: clef-node/boot.sh
        target: /root/boot.sh
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.10
    command: /root/boot.sh
  node1:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node1-volume
        target: /root/.ethereum
      - type: bind
        source: geth-node1/etherbase
        target: /root/etherbase
        read_only: true
      - type: bind
        source: geth-node1/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: geth-node/boot-with-clef.sh
        target: /root/boot.sh
        read_only: true
      - type: bind
        source: bootnode/enode
        target: /root/bootnode-enode
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.1
    command: /root/boot.sh 5
    depends_on:
      - bootnode
      - node1-clef
  node2-clef:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node2-volume
        target: /root/.ethereum
        read_only: true
      - type: volume
        source: clef-node2-volume
        target: /root/.clef
      - type: bind
        source: clef-node2/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: clef-node/rules.js
        target: /root/rules.js
        read_only: true
      - type: bind
        source: clef-node/boot.sh
        target: /root/boot.sh
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.20
    command: /root/boot.sh
  node2:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node2-volume
        target: /root/.ethereum
      - type: bind
        source: geth-node2/etherbase
        target: /root/etherbase
        read_only: true
      - type: bind
        source: geth-node2/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: geth-node/boot-with-clef.sh
        target: /root/boot.sh
        read_only: true
      - type: bind
        source: bootnode/enode
        target: /root/bootnode-enode
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.2
    command: /root/boot.sh 5
    depends_on:
      - bootnode
      - node2-clef
  node3-clef:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node3-volume
        target: /root/.ethereum
        read_only: true
      - type: volume
        source: clef-node3-volume
        target: /root/.clef
      - type: bind
        source: clef-node3/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: clef-node/rules.js
        target: /root/rules.js
        read_only: true
      - type: bind
        source: clef-node/boot.sh
        target: /root/boot.sh
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.30
    command: /root/boot.sh
  node3:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node3-volume
        target: /root/.ethereum
      - type: bind
        source: geth-node3/etherbase
        target: /root/etherbase
        read_only: true
      - type: bind
        source: geth-node3/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: geth-node/boot-with-clef.sh
        target: /root/boot.sh
        read_only: true
      - type: bind
        source: bootnode/enode
        target: /root/bootnode-enode
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.3
    command: /root/boot.sh 5
    depends_on:
      - bootnode
      - node3-clef
  besu-node1:
    build:
      context: ./besu-node
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: besu-node1-volume
        target: /opt/besu/data
      - type: bind
        source: genesis.json
        target: /opt/besu/genesis.json
        read_only: true
      - type: bind
        source: geth-node1/enode
        target: /opt/besu/geth-node1-enode
        read_only: true
      - type: bind
        source: geth-node2/enode
        target: /opt/besu/geth-node2-enode
        read_only: true
      - type: bind
        source: geth-node3/enode
        target: /opt/besu/geth-node3-enode
        read_only: true
      - type: bind
        source: besu-node/boot.sh
        target: /opt/besu/boot.sh
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.4
    entrypoint: /opt/besu/boot.sh
  besu-node2:
    build:
      context: ./besu-node
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: besu-node2-volume
        target: /opt/besu/data
      - type: bind
        source: genesis.json
        target: /opt/besu/genesis.json
        read_only: true
      - type: bind
        source: geth-node1/enode
        target: /opt/besu/geth-node1-enode
        read_only: true
      - type: bind
        source: geth-node2/enode
        target: /opt/besu/geth-node2-enode
        read_only: true
      - type: bind
        source: geth-node3/enode
        target: /opt/besu/geth-node3-enode
        read_only: true
      - type: bind
        source: besu-node/boot.sh
        target: /opt/besu/boot.sh
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.5
    entrypoint: /opt/besu/boot.sh
  bootnode:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: bind
        source: bootnode/boot.key
        target: /root/boot.key
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.100
    command: bootnode -nodekey /root/boot.key -nat extip:172.29.0.100 -netrestrict 172.29.0.0/16
networks:
  default:
   driver: bridge
   ipam:
    config:
      - subnet: 172.29.0.0/16
        gateway: 172.29.0.200
volumes:
  clef-node1-volume:
    external: true
  clef-node2-volume:
    external: true
  clef-node3-volume:
    external: true
  geth-node1-volume:
    external: true
  geth-node2-volume:
    external: true
  geth-node3-volume:
    external: true
  besu-node1-volume:
    external: true
  besu-node2-volume:
    external: true
