services:
  geth-node:
    image: try-ethereum/geth-node
    build:
      context: geth-node/.devcontainer
      dockerfile: Dockerfile
      target: devcontainer
    volumes:
      - .:/workspaces:cached
      - geth-volume:/var/geth:rw
    command: sleep infinity
volumes:
  geth-volume:
    external: true
