services:
  geth-node:
    image: try-ethereum/geth-node:v1.11.5
    volumes:
      - .:/workspaces:cached
      - geth-volume:/var/geth:rw
    command: sleep infinity
volumes:
  geth-volume:
    external: true
