services:
  node1:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node1-volume
        target: /root/.ethereum
      - type: bind
        source: geth-node1/etherbase
        target: /root/etherbase
        read_only: true
      - type: bind
        source: geth-node1/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: geth-node/boot.sh
        target: /root/boot.sh
        read_only: true
      - type: bind
        source: bootnode/enode.txt
        target: /root/bootnode-enode.txt
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.1
    command: /root/boot.sh
    depends_on:
      - bootnode
  node2:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node2-volume
        target: /root/.ethereum
      - type: bind
        source: geth-node2/etherbase
        target: /root/etherbase
        read_only: true
      - type: bind
        source: geth-node2/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: geth-node/boot.sh
        target: /root/boot.sh
        read_only: true
      - type: bind
        source: bootnode/enode.txt
        target: /root/bootnode-enode.txt
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.2
    command: /root/boot.sh
    depends_on:
      - bootnode
      - node1
  node3:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: volume
        source: geth-node3-volume
        target: /root/.ethereum
      - type: bind
        source: geth-node3/etherbase
        target: /root/etherbase
        read_only: true
      - type: bind
        source: geth-node3/PASSWORD
        target: /root/PASSWORD
        read_only: true
      - type: bind
        source: geth-node/boot.sh
        target: /root/boot.sh
        read_only: true
      - type: bind
        source: bootnode/enode.txt
        target: /root/bootnode-enode.txt
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.3
    command: /root/boot.sh
    depends_on:
      - bootnode
      - node1
      - node2
  bootnode:
    image: ethereum/client-go:alltools-v1.11.5
    volumes:
      - type: bind
        source: bootnode/boot.key
        target: /root/boot.key
        read_only: true
    networks:
      default:
        ipv4_address: 172.29.0.100
    command: bootnode -nodekey /root/boot.key -nat extip:172.29.0.100 -netrestrict 172.29.0.0/16
networks:
  default:
   driver: bridge
   ipam:
    config:
      - subnet: 172.29.0.0/16
        gateway: 172.29.0.200
volumes:
  geth-node1-volume:
    external: true
  geth-node2-volume:
    external: true
  geth-node3-volume:
    external: true
